name: party_decoration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  json_serializable: ^6.11.2


flutter:
  uses-material-design: true
